- Makefile
- iep-config/src/main/java/com/netflix/iep/config/Configuration.java
- iep-config/src/main/java/com/netflix/iep/config/DefaultValue.java
- iep-config/src/main/java/com/netflix/iep/config/IConfiguration.java
- iep-config/src/main/java/com/netflix/iep/config/MapConfiguration.java
- iep-config/src/main/java/com/netflix/iep/config/PersistedPropertiesConfiguration.java
- iep-config/src/main/java/com/netflix/iep/config/Strings.java
- iep-config/src/main/java/com/netflix/iep/config/SystemPropertyConfiguration.java
- iep-config/src/test/java/com/netflix/iep/config/ConfigurationTests.java
- iep-config/src/test/java/com/netflix/iep/config/PropertyFileConfigurationTests.java
- iep-config/src/test/java/com/netflix/iep/config/ResourceConfiguration.java
- iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java
- iep-nflxenv/src/test/scala/com/netflix/iep/NetflixEnvironmentSuite.scala
- project/License.scala
- project/sbt
1. Run formatLicenseHeaders
2. Fix project/sbt to use HOME if WORKSPACE isn't set
> fix build issues for travis

- project/Build.scala
- project/Dependencies.scala
Upgrade eureka versions and remove hacks to force
newer ribbon dependency.
> eureka-client-1.1.150

- iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/ArchaiusModule.java
- iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/RemoteProperties.java
- iep-module-archaius2/src/main/resources/META-INF/services/com.google.inject.Module
- iep-module-archaius2/src/main/resources/reference.conf
- project/Build.scala
- project/BuildSettings.scala
- project/Dependencies.scala
Init an app config and hook it up to our dynamic
properties source.
> initial module for archaius 2

- iep-rxhttp/src/main/java/com/netflix/iep/http/RxHttp.java
* add getJson/deleteJson to go along with existing
postJson and putJson
* postJson/putJson now set accept json header to
expect json output
> make json helpers more consistent

- iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/ArchaiusModule.java
- iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/OverrideModule.java
- iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/RemotePropertiesCallable.java
- iep-module-archaius2/src/main/resources/META-INF/services/com.google.inject.Module
Switch to an override module to make it work with guice4. Add
some additional debug logging around the polling.
> adjustments to app config

- iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaHandler.java
- iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaModule.java
- iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaService.java
- iep-module-eureka/src/main/java/com/netflix/iep/eureka/HandlerProvider.java
- iep-service/src/main/java/com/netflix/iep/service/AbstractService.java
- iep-service/src/main/java/com/netflix/iep/service/Service.java
- iep-service/src/main/java/com/netflix/iep/service/ServiceManager.java
- iep-service/src/main/java/com/netflix/iep/service/State.java
- project/Build.scala
- project/Dependencies.scala
Minimal service abstraction for binding some parts of the
application that are critical to the healthcheck.
> minimal service abstraction

- iep-config/src/main/java/com/netflix/iep/config/ConfigModule.java
With rc.16 the CompositeConfig for ApplicationLayer is what
gets injected to provied the final Config.
> fix config injection

- iep-governator/src/main/java/com/netflix/iep/gov/Governator.java
The module `iep-module-archaius1` should be used
instead. Addresses #100.
> remove init archaius

- iep-guice/src/main/java/com/netflix/iep/guice/AnnotationUtils.java
- iep-guice/src/main/java/com/netflix/iep/guice/LifecycleModule.java
- iep-guice/src/test/java/com/netflix/iep/guice/LifecycleTest.java
Instances coming from providers were getting ignored for the
lifecycle.
> use ProvisionListener instead of TypeListener

- iep-module-karyon3/src/main/java/com/netflix/iep/karyon3/JarHandler.java
- iep-module-karyon3/src/main/java/com/netflix/iep/karyon3/KaryonModule.java
Add bindings for some of the core karyon3 resources. For
the jars compatiblity endpoint base it off the JarsAdminResource.
> add karyon3 core resources

- project/Dependencies.scala
Seems to fix strange timeout issue we were only seeing on
travis build for 0.2.x branch. Not sure why.
> rxjava-1.0.14

- project/Dependencies.scala
Fixes gzip size issue on admin.
> karyon 3.0.1-rc.13

- iep-rxhttp/src/main/java/com/netflix/iep/http/ByteBufs.java
- iep-rxhttp/src/main/java/com/netflix/iep/http/ServerSentEvent.java
- iep-rxhttp/src/test/java/com/netflix/iep/http/ByteBufsTest.java
- iep-rxhttp/src/test/java/com/netflix/iep/http/ServerSentEventTest.java
Adds the simple line decoder from netty and a helper to
parse server sent events.
> helper for decoding sse from Observable<ByteBuf>

- iep-guice/src/main/java/com/netflix/iep/guice/BaseModule.java
- iep-guice/src/test/java/com/netflix/iep/guice/BaseModuleTest.java
For right now it just has a getConstructor for quickly
creating a binding to class with a single constructor
and no explict Inject annotations.
> add BaseModule with binding helpers

- iep-rxhttp/src/main/java/com/netflix/iep/http/EurekaServerRegistry.java
Refresh the server list when there is a cache refreshed
event instead of expiring after 15s. This should reduce
the number of times the server list has to get recreated
as well as reducing the latency for picking up changes to
the set of servers.
> use EurekaEventListener to refresh server list

- project/Dependencies.scala
> update to rxnetty 0.4.16

- project/Dependencies.scala
This version pulls in netty-4.1.5.Final which fixes
a bug with users running under tomcat with tomcat-native
enabled.
> rxnetty 0.4.19

- iep-nflxenv/src/main/resources/reference.conf
Update the account-env setting to try NETFLIX_ENVIRONMENT
which should be correct if running with recent userdata.
> update account-env setting

- iep-module-userservice/src/main/java/com/netflix/iep/userservice/EmployeeUserService.java
- iep-module-userservice/src/test/java/com/netflix/iep/userservice/EmployeeUserServiceTest.java
The term_date can be set if someone leaves and then
comes back.
> use active_status rather than term_date

- project/Dependencies.scala
> eureka 1.6.2

- iep-module-aws/src/main/java/com/netflix/iep/aws/Pagination.java
- iep-module-aws/src/test/java/com/netflix/iep/aws/PaginationTest.java
The ListResourceRecordSets call uses a set of
markers instead of just one with different names
than ListHostedZones.
> fix pagination for resource record sets

- README.md
Updates the README with a better explanation of the project
and how it fits in with other NetflixOSS.
> docs: update readme for the root

- iep-admin/src/main/java/com/netflix/iep/admin/endpoints/BaseServerEndpoint.java
- iep-admin/src/test/java/com/netflix/iep/admin/endpoints/BaseServerEndpointTest.java
Allows the legacy metrics-explorer view to work with apps
that are using this admin.
> fix #335, backwards compatible /metrics endpoint

- iep-guice/src/test/java/com/netflix/iep/guice/LifecycleTest.java
Verify behavior of using PostConstruct and PreDestroy
on the provider.
> add test case for provider lifecycle

- iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
- project/Dependencies.scala
> aws-sdk-java-v2 preview 12

- build.sbt
- iep-servergroups/README.md
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/EddaLoader.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/EurekaLoader.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/GroupService.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/Instance.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/Loader.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/ServerGroup.java
- iep-servergroups/src/test/java/com/netflix/iep/servergroups/EddaLoaderTest.java
- iep-servergroups/src/test/java/com/netflix/iep/servergroups/EurekaLoaderTest.java
- iep-servergroups/src/test/java/com/netflix/iep/servergroups/GroupServiceTest.java
- iep-servergroups/src/test/java/com/netflix/iep/servergroups/InstanceTest.java
- iep-servergroups/src/test/java/com/netflix/iep/servergroups/ServerGroupTest.java
- iep-servergroups/src/test/java/com/netflix/iep/servergroups/TestHttpClient.java
- iep-servergroups/src/test/resources/edda-ec2.json
- iep-servergroups/src/test/resources/edda-no-instances.json
- iep-servergroups/src/test/resources/eureka-dup.json
- iep-servergroups/src/test/resources/eureka-ec2.json
- iep-servergroups/src/test/resources/eureka-invalid.json
- iep-servergroups/src/test/resources/eureka-ip.json
- iep-servergroups/src/test/resources/eureka-no-id.json
- iep-servergroups/src/test/resources/eureka-no-ip.json
- iep-servergroups/src/test/resources/eureka-titus.json
Creates a merged view of server groups using both Edda
and Eureka.
> add library for getting server groups

- iep-config/src/main/java/com/netflix/iep/config/ConfigFile.java
- iep-config/src/main/java/com/netflix/iep/config/Resources.java
- iep-config/src/main/java/com/netflix/iep/config/ScopedPropertiesLoader.java
- iep-config/src/main/java/com/netflix/iep/config/TestResourceConfiguration.java
Help reduce guava usage as it is a problematic dependency.
> remove guava usage from iep-config

- iep-admin/src/main/java/com/netflix/iep/admin/AdminServer.java
- iep-admin/src/test/java/com/netflix/iep/admin/endpoints/SpectatorEndpointTest.java
- iep-config/src/main/java/com/netflix/iep/config/DynamicPropertiesConfiguration.java
- iep-config/src/test/java/com/netflix/iep/config/ConfigurationTests.java
- iep-config/src/test/java/com/netflix/iep/config/PropertyFileConfigurationTests.java
- iep-module-admin/src/main/java/com/netflix/iep/admin/guice/AdminModule.java
- iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/OverrideModule.java
- iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaModule.java
- iep-ses/src/main/java/com/netflix/iep/ses/EmailRequestBuilder.java
- iep-ses/src/test/java/com/netflix/iep/ses/EmailRequestBuilderTest.java
Cleanup a number of deprecation warnings and remove some
deprecated methods.
> fix deprecation warnings

- CONTRIBUTING.md
- iep-module-aws2/README.md
Fix a couple of broken links in some of the markdown
pages.
> fix markdown links

- Makefile
See Netflix/atlas#1016 for more details.
> explicitly fetch tags for build

- iep-admin/src/main/java/com/netflix/iep/admin/RequestHandler.java
- iep-config/src/main/java/com/netflix/iep/config/Configuration.java
- iep-config/src/main/java/com/netflix/iep/config/DynamicPropertiesConfiguration.java
- iep-config/src/main/java/com/netflix/iep/config/Strings.java
- iep-config/src/main/java/com/netflix/iep/config/TestResourceConfiguration.java
- iep-config/src/test/java/com/netflix/iep/config/ConfigFileTests.java
- iep-config/src/test/java/com/netflix/iep/config/ConfigurationTests.java
- iep-guice/src/main/java/com/netflix/iep/guice/Args.java
- iep-module-admin/src/main/java/com/netflix/iep/admin/guice/AdminModule.java
- iep-module-aws/src/main/java/com/netflix/iep/aws/AwsClientFactory.java
- iep-module-aws/src/main/java/com/netflix/iep/aws/Pagination.java
- iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
- iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
- iep-module-leader/src/test/java/com/netflix/iep/leader/LeaderServiceTest.java
- iep-rxhttp/src/main/java/com/netflix/iep/http/ServerSentEvent.java
- iep-rxhttp/src/test/java/com/netflix/iep/http/ByteBufsTest.java
- iep-rxhttp/src/test/java/com/netflix/iep/http/RxHttpTest.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/JsonUtils.java
Removes some spurious println statements from tests. Also
fixes a few warnings.
> remove spurious println from tests

- project/Dependencies.scala
Pick up fix for DNS resolution with netty client.
https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#21056-2020-01-24
> aws-sdk-java-v2 2.10.56

- project/GitVersion.scala
> update base version for master branch

- .travis.yml
Ensure libraries work on 2LTS and latest.
> add jdk14 to travis matrix

- iep-ses/src/main/java/com/netflix/iep/ses/EmailRequestBuilder.java
Simplify conditions to remove unnecessary null checks.
> ses: clean up warnings

- iep-nflxenv/src/main/java/com/netflix/iep/config/ConfigListener.java
- iep-nflxenv/src/main/java/com/netflix/iep/config/DynamicConfigManagerImpl.java
- iep-nflxenv/src/test/java/com/netflix/iep/config/DynamicConfigManagerTest.java
Adds helpers to create listeners for a particular property
instead of the config or sub-config.
> add helpers to create listeners for a property

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .travis.yml
Test out build and release using GitHub Actions.
> enable github actions

- project/SonatypeSettings.scala
Change it to reflect Netflix instead of individual.
> update project hosting information for POM

- project/GitVersion.scala
Also fix build deprecation warning.
> update base version to 3.0.x

- .github/workflows/pr.yml
Drop jdk15 and add jdk16 to build.
> update CI builds to use jdk16

- iep-module-atlas/src/main/java/com/netflix/iep/atlas/AtlasRegistryService.java
Remove duplicate start call for the AtlasRegistry.
> remove duplicate start for registry

- iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java
- iep-nflxenv/src/test/java/com/netflix/iep/NetflixEnvironmentTest.java
This work supports the Titus Multi-Container Tagging Specification.
> add nf.container and nf.process common tags

- project/Dependencies.scala
Pull in fix for [CVE-2020-36518].
[CVE-2020-36518]: https://nvd.nist.gov/vuln/detail/CVE-2020-36518
> jackson 2.13.2.2

- project/GitVersion.scala
Update main branch to use base version of 4.0.x in
preparation for changes to support Spring.
> update base version to 4.0.x

- iep-spring/src/main/java/com/netflix/iep/spring/Main.java
Can be useful for testing in other projects.
> make context accessor public

- iep-spring-dynconfig/src/main/java/com/netflix/iep/dynconfig/DynamicConfigConfiguration.java
Add annotation so it will get picked up when scanning.
> annotation dynconfig configuration class

- iep-spring-admin/src/main/java/com/netflix/iep/admin/spring/SpringEndpoint.java
- iep-spring-admin/src/test/java/com/netflix/iep/admin/spring/SpringEndpointTest.java
Include some additional information about where a
binding is coming from and what it depends on.
> add info to spring endpoint

- iep-spring-admin/src/main/java/com/netflix/iep/admin/spring/AdminConfiguration.java
- iep-spring-admin/src/main/java/com/netflix/iep/admin/spring/SpringBeansEndpoint.java
- iep-spring-admin/src/main/java/com/netflix/iep/admin/spring/SpringEnvEndpoint.java
- iep-spring-admin/src/test/java/com/netflix/iep/admin/spring/SpringBeansEndpointTest.java
- iep-spring-admin/src/test/java/com/netflix/iep/admin/spring/SpringEnvEndpointTest.java
Add admin view for spring properties to help with
debugging.
> add view of spring properties

- iep-spring-atlas/src/main/java/com/netflix/iep/atlas/AtlasRegistryService.java
- iep-spring-atlas/src/test/java/com/netflix/iep/atlas/AtlasRegistryServiceTest.java
Look for properties set based on cloud data to disable Atlas publishing by default when running locally. This can be overridden by an explicit setting to enable.
> disable publishing when running locally

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- project/BuildSettings.scala
In preparation for Spring 6, drop support for jdk8 and jdk11.
> set baseline java version to 17

- build.sbt
- iep-admin/src/main/java/com/netflix/iep/admin/AdminEndpoint.java
- iep-service/src/main/java/com/netflix/iep/service/AbstractService.java
- iep-service/src/test/java/com/netflix/iep/service/DefaultClassFactoryTest.java
- iep-spring/src/test/java/com/netflix/iep/spring/LifecycleTest.java
- iep-spring/src/test/java/com/netflix/iep/spring/SpringClassFactoryTest.java
- project/Dependencies.scala
The only code changes are moving from javax to jakarta annotations.
> update to spring 6

- build.sbt
Jakarta Inject is not needed for this project.
> remove unnecessary deps for admin

- build.sbt
- iep-spring-leader-redis-cluster/README.md
- iep-spring-leader-redis-cluster/src/main/java/com/netflix/iep/leader/redis/RedisClusterLeaderClient.java
- iep-spring-leader-redis-cluster/src/main/java/com/netflix/iep/leader/redis/RedisClusterLeaderDatabase.java
- iep-spring-leader-redis-cluster/src/main/java/com/netflix/iep/leader/redis/RedisClusterLeaderDatabaseConfiguration.java
- iep-spring-leader-redis-cluster/src/main/resources/reference.conf
- iep-spring-leader-redis-cluster/src/test/java/com/netflix/iep/leader/redis/RedisClusterLeaderDatabaseTest.java
- project/Dependencies.scala
Add implementation of a leader database using redis instead of dynamodb.
> add leader database using redis (#561)

- iep-admin/src/main/java/com/netflix/iep/admin/EndpointMapping.java
- iep-admin/src/main/java/com/netflix/iep/admin/endpoints/JmxEndpoint.java
- iep-admin/src/main/java/com/netflix/iep/admin/endpoints/SpectatorEndpoint.java
- iep-admin/src/test/java/com/netflix/iep/admin/AdminServerTest.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/EurekaLoader.java
- iep-servergroups/src/main/java/com/netflix/iep/servergroups/ServerGroup.java
- iep-ses/src/main/java/com/netflix/iep/ses/Attachment.java
- iep-ses/src/main/java/com/netflix/iep/ses/EmailRequestBuilder.java
- iep-spring-leader-dynamodb/src/main/java/com/netflix/iep/leader/dynamodb/DynamoDbLeaderDatabase.java
- iep-spring-leader-redis-cluster/src/main/java/com/netflix/iep/leader/redis/RedisClusterLeaderClient.java
- iep-spring-leader-redis-cluster/src/main/java/com/netflix/iep/leader/redis/RedisClusterLeaderDatabase.java
- iep-spring-leader-redis-cluster/src/test/java/com/netflix/iep/leader/redis/RedisClusterLeaderDatabaseTest.java
- iep-spring-leader/src/test/java/com/netflix/iep/leader/LeaderServiceTest.java
- iep-spring/src/test/java/com/netflix/iep/spring/LifecycleTest.java
Cleanup some warnings and update some code to
leverage newer language features.
> fix misc warnings

- .github/workflows/snapshot.yml
> ci: enable snapshots for version branches

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
Older versions use a deprecated version of node.
> update github action versions

- iep-admin/src/main/java/com/netflix/iep/admin/AccessLogHandler.java
Ensure they are reported as server metrics rather than client metrics.
> fix ipc metrics for admin

- iep-service/src/main/java/com/netflix/iep/service/ClassFactory.java
- iep-service/src/main/java/com/netflix/iep/service/DefaultClassFactory.java
- iep-spring/src/main/java/com/netflix/iep/spring/SpringClassFactory.java
Update ClassFactory to support a method to verify the dependencies for a given class without creating it.
> service: add method to verify dependencies

- project/Dependencies.scala
Pull in latest version with netty patch.
> update to aws-sdk 2.30.17

- build.sbt
- iep-spring-sbhealth/src/main/java/com/netflix/iep/sbhealth/IepServiceHealthIndicator.java
- iep-spring-sbhealth/src/test/java/com/netflix/iep/sbhealth/IepServiceHealthIndicatorTest.java
- project/Dependencies.scala
Adds library that integrates the ServiceManager with the SpringBoot HealthIndicator.
> add library for SpringBoot health

- .github/dependabot.yml
Try out dependabot for keeping actions up to date.
> add dependabot config for actions
