Netflix/iep

iep-module-rxnetty/src/main/java/com/netflix/iep/rxnetty/RxNettyModule.java
iep-module-rxnetty/src/main/resources/META-INF/services/com.google.inject.Module
project/Build.scala
project/Dependencies.scala

Right now all it does is set it to use the spectator
metrics listener:
https://github.com/ReactiveX/RxNetty/tree/0.x/rxnetty-spectator

module for configuring rxnetty

---

iep-rxhttp/src/main/java/com/netflix/iep/http/ServerEntry.java

When a vip didn't have any servers registered, a ```java.lang.ArithmeticException``` was being thrown.

Return an empty list of servers if there are no servers in the registry

---

iep-rxhttp/src/main/java/com/netflix/iep/http/RedirectHandler.java

Do not attempt to follow a redirect on a 304.

Do not redirect on "Not Modified"

---

project/Build.scala
project/Dependencies.scala

To make sure we get a consistent version of guice dependendencies
this change adds an explicit dependency on all guice extensions used
by governator.

explicitly specify all guice deps

---

project/Build.scala
project/Dependencies.scala

Gradle coordinates for the libraries have changed so the
old 1.x archaius-core can be used without having to explicitly
add in both the 2.x core and legacy. The 2.x legacy lib isn't
needed anymore.

archaius-2.0.0-rc.8

---

iep-config/src/main/java/com/netflix/iep/config/ConfigModule.java

```
@400000005538822500e5261c 1) No implementation for com.netflix.archaius.AppConfig was bound.
@400000005538822500e5261c  at com.netflix.iep.config.ConfigModule$OverrideModule.configure(ConfigModule.java:63) (via modules: com.netflix.iep.config.ConfigModule -> com.google.inject.util.Modules$OverrideModule -> com.netflix.iep.config.ConfigModule$OverrideModule)
@400000005538822500e56884
@400000005538822500e56c6c 2) A binding to com.netflix.archaius.AppConfig was already configured at com.netflix.iep.config.ConfigModule$OverrideModule.createAppConfig() (via modules: com.netflix.iep.config.ConfigModule -> com.google.inject.util.Modules$OverrideModule -> com.netflix.iep.config.ConfigModule$OverrideModule).
@400000005538822500e5a704  at …
```

fix config binding

---

iep-module-archaius1/README.md
iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/Archaius2Listener.java
iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/ArchaiusModule.java
iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/ConfigProvider.java
iep-module-archaius1/src/test/java/com/netflix/iep/archaius1/ArchaiusModuleTest.java
iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/OverrideModule.java
project/Build.scala

This should allow us to transition loading to archaius2
and also means that dynamic properties from platformservice
will work when using archaius1.

make archaius2 the override layer for archaius1

---

iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/Archaius1Module.java
iep-module-archaius1/src/main/resources/META-INF/services/com.google.inject.Module
iep-module-archaius1/src/test/java/com/netflix/iep/archaius1/ArchaiusModuleTest.java
project/Build.scala

The iep-module-archaius1 no longer forces the use of
iep-module-archaius2.

allow archaius1 to be used with any v2 config

---

iep-guice/src/main/java/com/netflix/iep/guice/GuiceHelper.java
project/Dependencies.scala

Rename Governator class to GuiceHelper as it is no
longer using governator and is just a minimal helper
for guice4.

rename class to avoid ambiguity

---

iep-rxhttp/src/main/java/com/netflix/iep/http/ClientConfig.java
iep-rxhttp/src/main/java/com/netflix/iep/http/ErrorRetryHandler.java
iep-rxhttp/src/test/java/com/netflix/iep/http/RxHttpTest.java

This PR adds a new config option: RetryReadTimeouts which specifies whether read timeouts should be retried.

Add RetryReadTimeouts config option

---

iep-module-archaius1/src/test/java/com/netflix/iep/archaius1/ArchaiusModuleTest.java
project/Dependencies.scala

Fixes configuration loading if the static block of
ConfigurationManager is executed before the module
for connecting archaius1 to archaius2.

archaius 2.0.0-rc.12

---

iep-guice/src/main/java/com/netflix/iep/guice/LifecycleModule.java
iep-module-karyon/src/main/java/com/netflix/iep/karyon/KaryonModule.java

Fix NullPointerException if some of the property keys exist
but have a null value.
```
Caused by: java.lang.NullPointerException
at java.util.Hashtable.put(Hashtable.java:459) ~[?:1.8.0_45]
at java.util.Properties.setProperty(Properties.java:166) ~[?:1.8.0_45]
at com.netflix.iep.karyon.KaryonModule$1.overrideProperties(KaryonModule.java:52) ~[iep-module-karyon-0.1.23-SNAPSHOT.jar:0.1.23-SNAPSHOT]
at netflix.admin.AdminExplorerManager.initialize(AdminExplorerManager.java:44) ~[karyon2-admin-2.7.1.jar:2.7.1]
... 83 more
```

skip properties with null values

---

iep-config/src/main/java/com/netflix/iep/config/ConfigModule.java
iep-module-archaius1/src/test/java/com/netflix/iep/archaius1/ArchaiusModuleTest.java
iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java
iep-platformservice/src/test/java/com/netflix/iep/platformservice/PlatformServiceModuleTest.java
project/Dependencies.scala

Fixes support for archaius1 dynamic properties when using
the bridge. `OverrideLayer` was renamed to `RemoteLayer`.

archaius-2.0.0-rc.14

---

iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaModule.java
iep-module-eureka/src/main/java/com/netflix/iep/eureka/InstanceInfoProvider.java
iep-module-eureka/src/test/java/com/netflix/iep/eureka/EurekaModuleTest.java
iep-module-eureka/src/test/resources/eureka-client.properties

Injector couldn't be created using standalone guice:
```
1) No scope is bound to com.netflix.governator.guice.lazy.LazySingleton.
at com.netflix.appinfo.providers.EurekaConfigBasedInstanceInfoProvider.class(EurekaConfigBasedInstanceInfoProvider.java:26)
at com.netflix.iep.eureka.EurekaModule.configure(EurekaModule.java:44)
```
The instance info provider was wrapped to make it only
need the standard classes and a test case was added to
load using Guice without governator.

fix scope issue with eureka module

---

iep-module-jmxport/src/main/java/com/netflix/iep/jmxport/JmxPort.java
iep-module-jmxport/src/main/java/com/netflix/iep/jmxport/SingleInterfaceRMIServerSocketFactory.java

Porting in recent change to platform for jmx behavior.
By default restricts to only listen on localhost so the
user will need to use an ssh proxy to the instance. This
provides better security and auditing. If needed the host
system property can be set to allow connecting directly
to jmx after opening up the port in the instance firewall.

listen on a particular interface

---

iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/Archaius1Module.java
iep-module-archaius1/src/test/java/com/netflix/iep/archaius1/ArchaiusModuleTest.java
iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaModule.java
iep-module-eureka/src/test/java/com/netflix/iep/eureka/EurekaModuleTest.java
iep-module-karyon/src/test/java/com/netflix/iep/karyon/KaryonModuleTest.java
iep-module-rxnetty/src/main/java/com/netflix/iep/rxnetty/RxNettyModule.java
iep-module-rxnetty/src/test/java/com/netflix/iep/rxnetty/RxNettyModuleTest.java

There are a number of apps internally that create a binding
of `Configuration` to something other than the main config.
Typically this is a binding for explorers with a small set
of properties. This change specifies a name for the binding
we care about to avoid the conflict.
For our use-cases this will always be an optional injection
and will get the static archaius instance as a fallback.

name the Configuration binding

---

iep-module-rxnetty/src/test/java/com/netflix/iep/rxnetty/RxNettyModuleTest.java
iep-module-rxnetty/src/test/resources/eureka-client.properties
project/Build.scala
project/Dependencies.scala

Note, eureka-client was changed to use the standard
`javax.inject` annotations instead of the annotations
from governator. Unfortunately this means that `DiscoveryClient`
can be pulled in via JIT injection, but without the right
settings in place it will throw exceptions about missing
serviceUrl.

eureka-client 1.2.0

---

iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/Archaius1Module.java
iep-module-archaius1/src/test/java/com/netflix/iep/archaius1/ArchaiusModuleTest.java

In more recent RCs the context is no longer automatically
updated based on the env variables in the baseami.

fix context for archaius1

---

iep-rxhttp/src/main/java/com/netflix/iep/http/RxHttp.java
iep-rxhttp/src/test/java/com/netflix/iep/http/RxHttpTest.java
project/Dependencies.scala

If the number of retries was set to 0, then the redirect
handler was never getting added.

fix redirect if num retries is set to 0

---

iep-rxhttp/src/main/java/com/netflix/iep/http/ByteBufs.java
iep-rxhttp/src/test/java/com/netflix/iep/http/ByteBufsTest.java

Currently provides transformers that can be used
with Observable.compose for:
* gzip compression/decompression
* aggregating to byte array
* aggregating to String
We'll look at an SSE decoder based on RxNetty's
version later.

helper utilities for Observable<ByteBuf>

---

iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java
iep-platformservice/src/main/resources/reference.conf
iep-platformservice/src/test/java/com/netflix/iep/platformservice/PlatformServiceModuleTest.java
iep-platformservice/src/test/resources/iep-test.conf

For running outside of the main account there are a handful
of properties where we need different settings. The need for
this should get reduced over time as we make things more
consistent.
Also sets up aliases for common env settings with defaults
so it is easier to run locally.

allow for config specific to environment

---

iep-rxhttp/src/main/java/com/netflix/iep/http/EurekaServerRegistry.java

Makes iep-rxhttp usable from Spring when the EurekaClient interface has a proxy around it.

Use EurekaClient instead of DiscoveryClient

---

iep-module-karyon3/src/main/java/com/netflix/iep/karyon3/CompatModule.java
iep-module-karyon3/src/main/java/com/netflix/iep/karyon3/NotFoundHandler.java

Default 404 handler doesn't properly close the stream
so we accumulate sockets in a CLOSE_WAIT state.
Also has incorrect content type.

fix 404 handler for admin

---

iep-rxhttp/src/main/java/com/netflix/iep/http/ErrorRetryHandler.java
iep-rxhttp/src/main/java/com/netflix/iep/http/ServerEntry.java
iep-rxhttp/src/test/java/com/netflix/iep/http/ServerEntryTest.java

Since retries are for the next server in the list, an unknown
host exception should be retried as it may only be one bad
server in the list.

retry on UnknownHostException

---

iep-guice/src/main/java/com/netflix/iep/guice/ClassFactoryProvider.java
iep-guice/src/main/java/com/netflix/iep/guice/LifecycleModule.java
iep-guice/src/test/java/com/netflix/iep/guice/GuiceClassFactoryTest.java
iep-service/src/main/java/com/netflix/iep/service/ClassFactory.java
iep-service/src/main/java/com/netflix/iep/service/CreationException.java
iep-service/src/main/java/com/netflix/iep/service/DefaultClassFactory.java
iep-service/src/test/java/com/netflix/iep/service/DefaultClassFactoryTest.java
project/Build.scala

Helper to use the injector for use-cases where we have class
names specified in the config file. The lib providing the
class needs to follow some simple conventions, but doesn't
need to have any dependency on a specific injection framework.

factory for creating class instance from name

---

iep-rxhttp/src/main/java/com/netflix/iep/http/RxHttp.java

Switch to computeIfAbsent to make logic more clear
for getting the total strategy used to limit max
connections.

simplify getting total strategy

---

iep-guice/src/main/java/com/netflix/iep/guice/Args.java
iep-guice/src/main/java/com/netflix/iep/guice/Main.java
iep-guice/src/test/java/com/netflix/iep/guice/MainTest.java
iep-guice/src/test/java/com/netflix/iep/guice/TestModule.java
iep-guice/src/test/java/com/netflix/iep/guice/TestService.java
iep-guice/src/test/resources/META-INF/services/com.google.inject.Module
project/Build.scala

For simple apps that just define a set of Service binding
for use with ServiceManager, the main class is pretty much
the same. This change adds a simple main class that can be
reused for those applications.

main class for apps that just use ServiceManager

---

project/Dependencies.scala

This release allows us to work with netty 4.1.x.Final
instead of the older 4.1 beta release. We have seen
soem issues with mixed versions.

update to rxnetty 0.4.17

---

build.sbt
iep-module-rxnetty/src/main/java/com/netflix/iep/rxnetty/RxNettyModule.java

We typically use the http request level metrics to
understand what the clients are doing. The lower level
rxnetty metrics aren't used much and don't follow
the recommended conventions so we would prefer not
to publish them for our apps by default.
An app owner can explicitly enable if they are still
desirable in certain use-cases.

remove rxnetty metrics module

---

iep-admin/src/main/java/com/netflix/iep/admin/endpoints/SpectatorEndpoint.java
iep-admin/src/test/java/com/netflix/iep/admin/endpoints/SpectatorEndpointTest.java

Fixes the toString representation of the OrQuery. It was
returning `:pr` instead of `:or`. Updates the test cases
to verify we get the same result from the toString output
of the query.

fix toString for OrQuery

---

iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaModule.java
project/Dependencies.scala

As of 1.6.0 an explicit binding is needed. Using the Jersey1
binding as that is the currently recommended and most tested
use. There is also a Jersey2 impl in 1.6.0.

fix #275, add binding for eureka optional args

---

build.sbt
iep-module-userservice/src/main/java/com/netflix/iep/userservice/AbstractUserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/CompositeUserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/Context.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/DepartedUserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/EmployeeUserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/SimpleUserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/UserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/UserServiceModule.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/UserUtils.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/WhitelistUserService.java
iep-module-userservice/src/main/resources/META-INF/services/org.google.inject.Module
iep-module-userservice/src/main/resources/reference.conf
iep-module-userservice/src/test/java/com/netflix/iep/userservice/CompositeUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/DepartedUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/EmployeeUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/SimpleUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/TestClient.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/UserServiceModuleTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/UserUtilsTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/WhitelistUserServiceTest.java
iep-module-userservice/src/test/resources/application.conf
project/Dependencies.scala

A number of internal apps have the same basic service
for looking up the set of users (email addresses) that
are valid for a given context.

move user service to common lib

---

iep-module-aws/src/main/java/com/netflix/iep/aws/AwsClientFactory.java
iep-module-aws/src/main/resources/reference.conf
iep-module-aws/src/test/java/com/netflix/iep/aws/AwsClientFactoryTest.java
iep-module-aws/src/test/resources/aws-client-factory.conf
iep-ses/src/test/java/com/netflix/iep/ses/EmailRequestBuilderTest.java

Fixes some deprecation warnings with recent AWS SDK by
switching to use the builders for clients. This change
also allows us to simplify the config because we only
need to know the region, not the full endpointn that we
need to construct. The config has been simplified to
only include overrides for services like SES and Route53
where the service is not available in all of the regions
where we need to access them.

switch to using builder for AWS clients

---

iep-module-atlas/src/main/java/com/netflix/iep/atlas/AtlasRegistryService.java
iep-module-atlas/src/main/resources/reference.conf
iep-module-atlas/src/test/java/com/netflix/iep/atlas/AtlasRegistryServiceTest.java
project/Dependencies.scala

Update the reference config and wrapper impl to support
the valid tag character settings that were added in 0.53.0:
https://github.com/Netflix/spectator/pull/378.

allow valid tag chars to be set in typesafe config

---

iep-nflxenv/src/main/resources/reference.conf

When working with groups outside Netflix based on
zerotocloud, this makes it easier to get started
spinning up a similar baseami.
Also adds the `domain` setting to allow an easy
substitution for creating DNS names in some configs.

allow CLOUD_ env vars if set to be used

---

iep-admin/src/main/java/com/netflix/iep/admin/endpoints/SpectatorEndpoint.java

Simplify the spectator endpoint to look for the
gauge type. This also works around an NPE with
ServoRegistry that is returning a null iterable.

update spectator endpoint for gauge type

---

project/BuildSettings.scala

Add the build date and number to the jar manifest
to aid in debugging.

add additional build metadata to jar

---

build.sbt
iep-module-aws/src/main/java/com/netflix/iep/aws/Pagination.java
iep-module-aws/src/test/java/com/netflix/iep/aws/PaginationTest.java
project/Dependencies.scala

Adds a utility class that helps take care of pagination
for common AWS requests. This is a simpler alternative
to [rx-aws-java-sdk](https://github.com/Netflix/rx-aws-java-sdk).
Helper methods are aviable to create a simple blocking
iterable or a publisher that can be used with any reactive
streams implementation.

utility class for helping with aws pagination

---

build.sbt
iep-module-aws/src/main/java/com/netflix/iep/aws/Pagination.java
iep-module-aws/src/test/java/com/netflix/iep/aws/PaginationTest.java
project/Dependencies.scala

It is based on `getLastEvaluatedKey` and
`setExclusiveStartKey`. The other change
is that the token no longer has to be a
String since DynamoDB uses a map.

handle pagination for DynamoDB queries

---

build.sbt
project/Dependencies.scala

It doesn't seem to be needed for our use-cases.

remove rxnetty-contexts dependency

---

iep-rxhttp/src/main/java/com/netflix/iep/http/RedirectHandler.java
iep-rxhttp/src/main/java/com/netflix/iep/http/RxHttp.java
iep-rxhttp/src/test/java/com/netflix/iep/http/RxHttpTest.java

The default redirect handler in RxNetty would cause them
to get followed even if disabled in RxHttp config. Also,
the redirect handler would always try to redirect at least
once.

fix ability to disable redirects with RxHttp

---

project/GitVersion.scala

This should cause the snapshots to publish
with the correct version.

update base version to 1.0.x

---

iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java
iep-platformservice/src/main/resources/reference.conf
iep-platformservice/src/test/java/com/netflix/iep/platformservice/PlatformServiceModuleTest.java
iep-platformservice/src/test/resources/a.conf
iep-platformservice/src/test/resources/application.conf
iep-platformservice/src/test/resources/c.conf

Adds a setting that can be used to load additional
config files based on settings in the base config.
This is typically used to load a config file specific
to a given cluster or environment that can be determined
from the environment variables on the system.

add support for loading context specific configs

---

project/Bintray.scala

The newer version of sbt-bintray adds the scm block
to the pom automatically. Having duplicate scm sections
in the pom causes errors when submitting to bintray (#321).

remove scm block from pom extras

---

project/Bintray.scala

Avoids errors when running on newer versions of
sbt:
```
[error] iep/project/Bintray.scala:30:19: The evaluation of `in` happens always inside a regular task.
[error]
[error] Problem: `in` is inside the if expression of a regular task.
[error]   Regular tasks always evaluate task inside the bodies of if expressions.
[error]
[error] Solution:
[error]   1. If you only want to evaluate it when the if predicate is true or false, use a dynamic task.
[error]   2. Otherwise, make the static evaluation explicit by evaluating `in` outside the if expression.
[error]
[error]         publishTo in bintray value
[error]                   ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

fix #320, move `in` outside the if

---

iep-config/src/main/java/com/netflix/iep/config/Strings.java
iep-config/src/test/java/com/netflix/iep/config/ConfigurationTests.java

The deprecated internal lib that predates this supports
java.time types instead of joda. With this change iep-config
will support both and so there will no longer be anything
preventing adoption and the old internal lib can go away.

support java.time types on config interface

---

project/BuildSettings.scala

Trying to clean up some of the noise in the build
logs. No one is paying attention to these warnings
and if there is a real compatibility problem it
should be caught in tests or the integration
environment.

disable eviction warnings for update task

---

build.sbt
iep-admin/src/main/java/com/netflix/iep/admin/AdminServer.java
iep-admin/src/test/java/com/netflix/iep/admin/AdminServerTest.java
iep-config/src/main/java/com/netflix/iep/config/DynamicPropertiesConfiguration.java
iep-guice/src/main/java/com/netflix/iep/guice/AnnotationUtils.java
iep-guice/src/main/java/com/netflix/iep/guice/PreDestroyList.java
iep-guice/src/test/java/com/netflix/iep/guice/LifecycleTest.java
iep-module-admin/src/test/java/com/netflix/iep/admin/GuiceDebugEndpointTest.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/Context.java
iep-rxhttp/src/main/java/com/netflix/iep/http/RxHttp.java
iep-rxhttp/src/test/java/com/netflix/iep/http/RxHttpTest.java
iep-service/src/main/java/com/netflix/iep/service/AbstractService.java
project/Dependencies.scala

Fixes #324. Avoids needing JSR250 annotations for simple
use-cases doing constructor injection and optionally a
destruction method indicated by being `AutoCloseable`.
Several known issues still:
1. Pre destroy list should be limited to singletons.
2. iep-service still needs `@PostConstruct` because it is
a base class and start cannot be invoked until after the
sub-class constructor is complete.

support AutoCloseable for DI lifecycle

---

project/sbt

The tty hack added in #326 causes the exit code to
be incorrect. This means the build can succeed when
it shouldn't.

remove tty hack

---

iep-guice/src/main/java/com/netflix/iep/guice/AnnotationUtils.java
iep-guice/src/main/java/com/netflix/iep/guice/LifecycleModule.java
iep-guice/src/test/java/com/netflix/iep/guice/LifecycleTest.java

If the binding is not a singleton, then a new instance
will be created each time. To avoid a memory leak these
objects will not be managed automatically, the user will
need to close them.

only manage shutdown lifecycle for singletons

---

.travis.yml
buildViaTravis.sh
project/Dependencies.scala
project/sbt

Updates the travis config so that we build on
both jdk8 and jdk9.

enable build for jdk9

---

.travis.yml
build.sbt
iep-module-aws2/README.md
iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsModule.java
iep-module-aws2/src/main/java/com/netflix/iep/aws2/Pagination.java
iep-module-aws2/src/main/resources/META-INF/services/com.google.inject.Module
iep-module-aws2/src/main/resources/reference.conf
iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsModuleTest.java
iep-module-aws2/src/test/java/com/netflix/iep/aws2/PaginationTest.java
iep-module-aws2/src/test/resources/aws-client-factory.conf
project/Dependencies.scala

Provides a module that works with the 2.x SDK. This is
experimental until the 2.x SDK is released and out of
developer preview mode. For now it is purely for early
adopters at Netflix to try out and provide feedback.
Note, jdk9 build is disabled until there is a fix of
either jackson 2.9.1 or in jdk9 itself for manifest
files that contain backticks. See:
https://bugs.openjdk.java.net/browse/JDK-8186334

add module with basic support for aws sdk 2.x

---

iep-module-aws2/src/main/resources/META-INF/services/com.google.inject.Module

It was referring to the name for the aws 1.x module.

fix module name for aws2 service file

---

iep-admin/src/test/java/com/netflix/iep/admin/endpoints/SpectatorEndpointTest.java
project/Dependencies.scala

spectator 0.58.0

---

.travis.yml
build.sbt
project/Dependencies.scala

Moves to jackson 2.9.1 to avoid problems with backticks
in the manifest:
https://bugs.openjdk.java.net/browse/JDK-8186334

reenable jdk9 build

---

project/Dependencies.scala

Update both the old archaius and 2.x version to the
latest releases. The 2.x release has performance fixes
to avoid using exceptions for control flow when accessing
the default values.

archaius 2.2.11 and 0.7.6

---

iep-module-aws/README.md
iep-module-aws/src/main/java/com/netflix/iep/aws/AwsClientFactory.java
iep-module-aws/src/test/java/com/netflix/iep/aws/AwsClientFactoryTest.java
iep-module-aws/src/test/resources/aws-client-factory.conf

There are two changes to make communicating with multiple
accounts from a single app easier:
1. The `newInstance` methods now have variants that take
an explicit account id. If the role-arn setting has an
account placeholder, then the explicit account id will
get used. Prior to this you would have to use separate
named blocks for each account which required a lot of
boilerplate.
2. Added `getInstance` methods that can be used to fetch
a common shared instance of a given client. With a lot
of the multi-client code something has to keep track
of the clients for each account. For simple uses they
can now just call `getInstance` on the factory.

make it easier to work with multiple accounts

---

build.sbt
iep-nflxenv/src/main/java/com/netflix/iep/config/ConfigManager.java
iep-nflxenv/src/test/java/com/netflix/iep/config/ConfigManagerTest.java
iep-nflxenv/src/test/resources/application.conf
iep-nflxenv/src/test/resources/classpath-include.conf
iep-nflxenv/src/test/resources/file-include.conf
iep-nflxenv/src/test/resources/iep-foo.conf
iep-nflxenv/src/test/resources/reference.conf
iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java
iep-platformservice/src/test/java/com/netflix/iep/platformservice/PlatformServiceModuleTest.java
iep-platformservice/src/test/resources/application.conf
iep-platformservice/src/test/resources/iep-foo.conf
iep-platformservice/src/test/resources/iep-main.conf

This makes it easier to reuse the loading we are using
for the typesafe config objects and in most cases can
be used as a substitute for `ConfigFactory.load` to make
those use-cases consistent. Unfortunately there are some
places that do not get the injected config and this helps
avoid inconsistencies.

add ConfigManager utility with iep loading logic

---

iep-rxhttp/src/main/java/com/netflix/iep/http/ClientConfig.java
iep-rxhttp/src/main/java/com/netflix/iep/http/RxHttp.java
iep-rxhttp/src/test/java/com/netflix/iep/http/ClientConfigTest.java
iep-rxhttp/src/test/java/com/netflix/iep/http/RxHttpTest.java

In some cases it is desirable to use a custom SSLContext
for the request. This allows the context to be provided
when performing the submit.

add support for providing an SSLContext

---

.travis.yml
build.sbt
iep-admin/src/test/java/com/netflix/iep/admin/endpoints/SystemPropsEndpointTest.java

Dropping jdk9 as there is no reason to use it over
jdk10 at this point.

update travis to build on jdk10/11-ea

---

iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java
iep-platformservice/src/test/java/com/netflix/iep/platformservice/PlatformServiceModuleTest.java
iep-platformservice/src/test/resources/application.conf

If the registry implementation needs to use the config, then
it will create a circular dependency between the config and
the registry instance and fail with:
```
Caused by: java.lang.IllegalStateException: This is a proxy
used to support circular references. The object we're
proxying is not constructed yet. Please wait until after
injection has completed to use this object.
```
To avoid this the config bindings will now use the Spectator
global registry internally. This breaks the cycle and still
allows the remote config loading to report metrics as long
as the registry binding adds itself to the global registry.

use global registry internal to config

---

iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
project/Dependencies.scala

A few package name changes and the timeout settings
have changed. Will look at that later when investigating
how to integrate basic IPC metrics.

aws-sdk-java 2.0.0-preview-10

---

iep-ses/src/main/java/com/netflix/iep/ses/Attachment.java
iep-ses/src/main/java/com/netflix/iep/ses/EmailHeader.java
iep-ses/src/test/resources/htmlWithInlineImage

This is used by GMail and possibly other mail clients to
show the user the name of an attachment. Before this change
it would show as `noname`.
/cc @ruchirj

include attachment name in Content-Type header

---

iep-ses/README.md
iep-ses/src/main/java/com/netflix/iep/ses/EmailHeader.java
iep-ses/src/main/java/com/netflix/iep/ses/EmailRequestBuilder.java
iep-ses/src/test/java/com/netflix/iep/ses/EmailRequestBuilderTest.java
iep-ses/src/test/resources/sendingAuthorizationFromArn
iep-ses/src/test/resources/sendingAuthorizationRequestParams

When using SES sending authorization and SendRawEmail, the
SourceArn will only work if the From address header is not
specified in the raw message. This is not clear from reading
the AWS documentation.
This change updates the helper to allow the FromArn to be
specified as part of the raw message which does work when
a from header is included. It also allows the from header
to be omitted now so that it can be included by calling
withSource on the SendRawEmailRequest object.
The readme has also been updated to cover the use with sending
authorization.

improve support for using sending authorization

---

build.sbt
iep-ses/README.md
iep-ses/src/main/java/com/netflix/iep/ses/EmailRequestBuilder.java
iep-ses/src/test/java/com/netflix/iep/ses/AwsSdk2Test.java

Adds helpers to get the `ByteBuffer` directly so it can
be used to construct the `RawMessage` object for either
v1 or v2 of the SDK. It is now fairly straightforward
to use with either version, but there is an explicit
dependency on v1 so it will get pulled in even if the
user is using v2.
Methods that refer to v1 classes have been deprecated so
we can remove the explicit dependency in iep-ses 2.0. At
that point the only version of the AWS libraries in the
classpath will be what the user depends on.

update iep-ses to work with aws-sdk-java-v2

---

iep-module-aws/src/main/java/com/netflix/iep/aws/Pagination.java
iep-module-aws/src/test/java/com/netflix/iep/aws/PaginationTest.java

This result object has both `withMarker` and `withNextMarker`.
The marker is what was used for the request that generated the
result and should get ignored for pagination. Before, if the
call resulted in multiple pages, the marker would always have
a value for the last page and cause it to indicate that there
was another request. However it was correctly updating the
request with the result of next marker so it would start over
from the beginning.
The test case has been updated to reproduce the issue.

fix endless loop for listHostedZones

---

build.sbt
iep-ses/src/main/java/com/netflix/iep/ses/EmailRequestBuilder.java
iep-ses/src/test/java/com/netflix/iep/ses/EmailRequestBuilderTest.java

Follow up on #369. This removes the hard dependency on the
v1 SDK. The user can then choose whether to pull in the SES
classes from the v1 or v2 SDK.

remove aws-java-sdk-ses dependency from iep-ses

---

.travis.yml

Current goal is to ensure the libraries work on jdk8, jdk11,
and latest.

add travis build for jdk12

---

iep-config/README.md
iep-config/src/main/java/com/netflix/iep/config/ConfigFile.java
iep-config/src/main/java/com/netflix/iep/config/ConfigModule.java
iep-config/src/main/java/com/netflix/iep/config/Configuration.java
iep-config/src/main/java/com/netflix/iep/config/DefaultValue.java
iep-config/src/main/java/com/netflix/iep/config/DynamicNoOpConfigModule.java
iep-config/src/main/java/com/netflix/iep/config/DynamicPropertiesConfiguration.java
iep-config/src/main/java/com/netflix/iep/config/IConfiguration.java
iep-config/src/main/java/com/netflix/iep/config/ScopedPropertiesLoader.java
iep-config/src/main/java/com/netflix/iep/config/Strings.java
iep-config/src/main/java/com/netflix/iep/config/TestResourceConfiguration.java
iep-module-archaius1/README.md
iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/Archaius1Module.java
iep-rxhttp/README.md
iep-rxhttp/src/main/java/com/netflix/iep/http/BasicServerRegistry.java
iep-rxhttp/src/main/java/com/netflix/iep/http/ByteBufs.java
iep-rxhttp/src/main/java/com/netflix/iep/http/EurekaServerRegistry.java
iep-rxhttp/src/main/java/com/netflix/iep/http/NetflixJsonObjectDecoder.java
iep-rxhttp/src/main/java/com/netflix/iep/http/RxHttp.java
iep-rxhttp/src/main/java/com/netflix/iep/http/Server.java
iep-rxhttp/src/main/java/com/netflix/iep/http/ServerRegistry.java
iep-rxhttp/src/main/java/com/netflix/iep/http/ServerSentEvent.java

Deprecates `iep-rxhttp`, `iep-config`, and `iep-module-archaius1`
libraries. These have been getting gradually phased out over time,
but will now provide deprecation warnings if used.

deprecate public classes for old libraries

---

iep-guice/src/main/java/com/netflix/iep/guice/GuiceHelper.java

For modules loaded using the ServiceLoader the user would
not have deprecation warnings in the code. This change adds
a warning log message to let them know at runtime.

log warning if loading deprecated module

---

iep-module-aws/README.md
iep-module-aws2/README.md
iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-module-aws2/src/main/resources/reference.conf
iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
iep-module-aws2/src/test/resources/aws-client-factory.conf

Updates the v2 client factory to support setting basic settings
on the client such as timeouts and headers. We do not currently
have a use-case for a custom HTTP client, so we'll look at
supporting that in the future if a use-case comes up.

support basic client settings for AWS v2

---

build.sbt

Most of the dependencies were for the pagination helper
which was removed and is not needed for the v2 SDK.

cleanup the dependencies for iep-module-aws2

---

iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
iep-module-aws2/src/test/resources/aws-client-factory.conf

Ports the changes in #345 to `iep-module-aws2`.

port multi-account support to aws2 helper

---

iep-guice/src/main/java/com/netflix/iep/guice/Main.java
iep-guice/src/test/java/com/netflix/iep/guice/MainTest.java

Adds support to the Main helper for passing in a set
of additional modules. A common use-case is custom
bindings for running locally.

allow additional modules for main

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/EddaLoader.java

Fix access so it can be created from outside of the
package.

make EddaLoader public

---

iep-module-userservice/src/main/java/com/netflix/iep/userservice/AbstractUserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/Context.java

A reference to the AtomicLong for the PolledMeter was not
retained so it would get garbage collected and stop reporting.
Also removes an unnecessary print stack trace call and updates
the client to set the endpoint for metrics. Since the remote
service in this case does not have the headers set, it is not
picked up automatically.

userservice: fix cache age metric

---

.travis.yml

The travis setup was still using the Oracle build.

switch to openjdk8

---

build.sbt
iep-servergroups/src/main/java/com/netflix/iep/servergroups/EddaLoader.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/EurekaLoader.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/JsonUtils.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/ServerGroup.java
iep-servergroups/src/test/resources/edda-ec2.json

Switches from using the high level object mapper to using
the streaming API directly. This avoids a lot of the
intermediate objects. Also changes the decompression to
occur while parsing to avoid a large allocation of a byte
array to hold the full uncompressed JSON payload.

reduce allocations for server group loaders

---

build.sbt
iep-leader-api/README.md
iep-leader-api/src/main/java/com/netflix/iep/leader/StandardLeaderElector.java
iep-leader-api/src/main/java/com/netflix/iep/leader/api/LeaderDatabase.java
iep-leader-api/src/main/java/com/netflix/iep/leader/api/LeaderElector.java
iep-leader-api/src/main/java/com/netflix/iep/leader/api/LeaderId.java
iep-leader-api/src/main/java/com/netflix/iep/leader/api/LeaderStatus.java
iep-leader-api/src/main/java/com/netflix/iep/leader/api/ResourceId.java
iep-leader-api/src/main/resources/reference.conf
iep-leader-api/src/test/java/com/netflix/iep/leader/StandardLeaderElectorTest.java
iep-leader-api/src/test/java/com/netflix/iep/leader/api/LeaderIdTest.java
iep-leader-api/src/test/java/com/netflix/iep/leader/api/ResourceIdTest.java
iep-leader-dynamodb/README.md
iep-leader-dynamodb/src/main/java/com/netflix/iep/leader/dynamodb/DynamoDbLeaderDatabase.java
iep-leader-dynamodb/src/main/java/com/netflix/iep/leader/dynamodb/DynamoDbLeaderModule.java
iep-leader-dynamodb/src/main/resources/META-INF/services/com.google.inject.Module
iep-leader-dynamodb/src/main/resources/reference.conf
iep-module-leader/README.md
iep-module-leader/src/main/java/com/netflix/iep/leader/LeaderModule.java
iep-module-leader/src/main/java/com/netflix/iep/leader/LeaderService.java
iep-module-leader/src/main/resources/META-INF/services/com.google.inject.Module
iep-module-leader/src/test/java/com/netflix/iep/leader/LeaderServiceTest.java
project/Dependencies.scala

This commit adds a leader election API for cases that a single entity
within a group should complete tasks for a set of resources. The
README.md files in the component modules have detailed information on
use.

Add leader election component

---

iep-guice/src/main/java/com/netflix/iep/guice/Main.java

The Guice Main helper's default to System.exit upon failure prevented
log statements that were critical to correctly diagnosing an error
from being emitted. The current implementation rethrows the exception
in the alternate case, so it seems equally reasonable to default to
false. This commit switches the default.

Invert exit on failure default

---

iep-leader-dynamodb/src/main/java/com/netflix/iep/leader/dynamodb/DynamoDbLeaderDatabase.java
iep-leader-dynamodb/src/main/resources/reference.conf

`tableActiveTimeout` did not match between use and definition.
The leader ID was not being set in the update attribute value.
Hyphenated DynamoDB table name.

Fix mismatch in config and missing attribute

---

iep-guice/src/main/java/com/netflix/iep/guice/Main.java

Upon discussion, though this seems simple on the surface, there are a
number of nuances that make this tricky to get right. For instance,
if a dependency has a non-daemon thread and the failure occurs in such a
way that a service such as discovery sees the app as in service, the app
could take traffic when it shouldn't.
The main change that occurred since this was put in place was a switch
to primarily use async loggers in the Insight Engineering apps. It was
previously observed that synchronous loggers would emit their logs, even
with the call to `System.exit()`. Ideally, we can restore that behavior
with async loggers, but that may also prove to not be easy.

Default to exit on failure

---

project/GitVersion.scala

It wasn't updated to 2.1.x so the snapshots were getting
published to 2.0.0.

fix base version for master

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/JsonUtils.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/EddaLoaderTest.java
iep-servergroups/src/test/resources/edda-overflow.json

In some cases we have seen Titus groups that incorrectly
report as having a desired size of `4294967291`. Rather
than fail to load the data, it will now ignore the size
and log a warning locally.

log warning instead of failing for bad group sizes

---

iep-nflxenv/src/main/resources/reference.conf

Update the reference.conf for iep-nflxenv with a default
value of an empty list of includes. This avoids an error
if the user hasn't explicitly set it.

add default for include

---

iep-guice/src/main/java/com/netflix/iep/guice/Main.java
iep-module-atlas/src/main/java/com/netflix/iep/atlas/AtlasRegistryService.java
iep-module-atlas/src/test/java/com/netflix/iep/atlas/AtlasRegistryServiceTest.java
iep-rxhttp/src/main/java/com/netflix/iep/http/ServerSentEvent.java
iep-rxhttp/src/test/java/com/netflix/iep/http/ByteBufsTest.java

1. Remove usage of unused config method from AtlasRegistry.
2. Fix usage of Class.newInstance().

fix deprecation warnings

---

build.sbt
iep-module-userservice/src/main/java/com/netflix/iep/userservice/Context.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/HttpUserService.java
iep-module-userservice/src/main/java/com/netflix/iep/userservice/UserServiceModule.java
iep-module-userservice/src/main/resources/reference.conf
iep-module-userservice/src/test/java/com/netflix/iep/userservice/DepartedUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/EmployeeUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/HttpUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/SimpleUserServiceTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/TestClient.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/UserServiceEndpointTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/UserServiceModuleTest.java
iep-module-userservice/src/test/java/com/netflix/iep/userservice/WhitelistUserServiceTest.java
iep-module-userservice/src/test/resources/application.conf
project/Dependencies.scala

Adds a new implementation of UserService that does an
inline call to check if an email is valid. This works
for the newer API internally and avoids the need to
cache the full set of users.
To reduce the cost of repeated checks it will cache
the result of checks for a period of time. Set to a
smaller value to be more responsive to new addresses.
The behavior can also be customized for a failure to
talk to the remote service. If it is a nice to have
check, then it might be better to treat it as valid
until it can be confirmed. Otherwise, an outage of
the remote service will prevent validation unless the
result has already been cached.

add userservice based on HTTP GET check

---

iep-module-eureka/README.md
iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaModule.java

For Insight we only use Eureka for heart-beats and their
are simpler solutions with less overhead now.

deprecate the Eureka client integration

---

iep-ses/src/main/java/com/netflix/iep/ses/EmailHeader.java
iep-ses/src/main/java/com/netflix/iep/ses/EmailRequestBuilder.java
iep-ses/src/test/java/com/netflix/iep/ses/EmailRequestBuilderTest.java
iep-ses/src/test/resources/sesConfigSet

The builder now has a method to add the header
for specifying the configuration set name.
Fixes #440

add support for SES configuration sets

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/ServerGroup.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/ServerGroupTest.java
project/Dependencies.scala
project/GitVersion.scala

Allows user to access shards that are specified as part
of the detail.

update servergroups library to support sharding

---

iep-nflxenv/src/main/java/com/netflix/iep/config/ConfigListener.java
iep-nflxenv/src/main/java/com/netflix/iep/config/ConfigManager.java
iep-nflxenv/src/main/java/com/netflix/iep/config/DynamicConfigManager.java
iep-nflxenv/src/main/java/com/netflix/iep/config/DynamicConfigManagerImpl.java
iep-nflxenv/src/test/java/com/netflix/iep/config/ConfigManagerTest.java
iep-nflxenv/src/test/java/com/netflix/iep/config/DynamicConfigManagerTest.java

Adds support for setting a dynamic override layer for the
ConfigManager. This can be used for updating the config
based on runtime sources such as the command line or a
remote property service.
This should allow us to phase out the usage of the
`atlas-config` library and simplify the overall config story.

support dynamic override for ConfigManager

---

build.sbt
iep-admin/src/main/java/com/netflix/iep/admin/AdminConfig.java
iep-admin/src/main/resources/reference.conf
iep-admin/src/test/java/com/netflix/iep/admin/AdminConfigTest.java
iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java

This allows the admin configuration to work even if the
platformservice module is not being used.

make default AdminConfig use reference.conf

---

iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java
iep-nflxenv/src/test/java/com/netflix/iep/NetflixEnvironmentTest.java

For some environments where the context ClassLoader is not
set properly using NetflixEnvironment would cause:
```
Caused by: com.typesafe.config.ConfigException$BugOrBroken: Context class loader is not set for the current thread; if Thread.currentThread().getContextClassLoader() returns null, you must pass a ClassLoader explicitly to ConfigFactory.load
at com.typesafe.config.ConfigFactory.checkedContextClassLoader(ConfigFactory.java:144)
at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:233)
at com.netflix.iep.NetflixEnvironment.<clinit>(NetflixEnvironment.java:26)
... 13 more
```
This change uses `ConfigManger.get()` that checks the
context ClassLoader and falls back to the ClassLoader for
the ConfigManager class if it is not set.

nflxenv: fallback if context classloader is null

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/EddaLoader.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/EddaLoaderTest.java
iep-servergroups/src/test/resources/edda-noip.json

Updates the server groups helper to ignore instances
coming back in the Edda response that are missing
required fields like the privateIpAddress. This allows
other instances to update and prevents having stale
data for everything. The failure will get logged.

ignore instances with missing fields

---

build.sbt

Makes it easier to spot in the recently used menu of the IDE.

rename root project to iep

---

iep-module-atlas/src/main/java/com/netflix/iep/atlas/AtlasRegistryService.java
iep-module-atlas/src/main/resources/reference.conf
project/Dependencies.scala

Updates the Atlas module to allow the rollup policy
added in Spectator 0.112.0 to be set with the config.

allow rollup policy to be set with config

---

iep-nflxenv/src/main/java/com/netflix/iep/config/ConfigListener.java
iep-nflxenv/src/main/java/com/netflix/iep/config/DynamicConfigManager.java
iep-nflxenv/src/main/java/com/netflix/iep/config/DynamicConfigManagerImpl.java
iep-nflxenv/src/main/java/com/netflix/iep/config/ListenerUtils.java
iep-nflxenv/src/test/java/com/netflix/iep/config/DynamicConfigManagerTest.java

Invokes the listener once with the current config when
added to intialize.

initialize the listener when added

---

build.sbt
iep-config/src/main/java/com/netflix/iep/config/ConfigFile.java
project/Dependencies.scala

Nashorn has been removed in jdk15. Move to Graal to make
it compile and run on newer JDKs.

switch to graal JS engine

---

build.sbt
iep-config/README.md
iep-module-archaius1/src/main/java/com/netflix/iep/archaius1/Archaius1Module.java
iep-module-archaius2/README.md
iep-module-archaius2/src/main/java/com/netflix/iep/archaius2/OverrideModule.java
iep-module-dynconfig/README.md
iep-module-dynconfig/src/main/java/com/netflix/iep/dynconfig/DynamicConfigModule.java
iep-module-dynconfig/src/main/java/com/netflix/iep/dynconfig/DynamicConfigService.java
iep-module-dynconfig/src/main/java/com/netflix/iep/dynconfig/PropsEndpoint.java
iep-module-dynconfig/src/main/resources/META-INF/services/com.google.inject.Module
iep-module-dynconfig/src/main/resources/reference.conf
iep-module-dynconfig/src/test/java/com/netflix/iep/dynconfig/DynamicConfigModuleTest.java
iep-module-dynconfig/src/test/java/com/netflix/iep/dynconfig/DynamicConfigServiceTest.java
iep-module-dynconfig/src/test/java/com/netflix/iep/dynconfig/PropsEndpointTest.java
iep-module-dynconfig/src/test/resources/a.conf
iep-module-dynconfig/src/test/resources/application.conf
iep-module-dynconfig/src/test/resources/c.conf
iep-module-dynconfig/src/test/resources/override.conf
iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java
iep-platformservice/src/main/java/com/netflix/iep/platformservice/PropertiesReader.java
iep-platformservice/src/test/java/com/netflix/iep/platformservice/PropertiesReaderTest.java

Deprecates the archaius2 module to make the config story
more clear and just standardize on Typesafe Config.
For cases where dynamic configuration is desirable a new
module `iep-module-dynconfig` has been added that works
with the ConfigManager from `iep-nflxenv`. It uses the
same properties and formats as the old modules so it can
easily be dropped in as long as you do not rely on the
Archaius config interfaces. This module also has an admin
endpoint for `/props` so it is easy to inspect the config
from the admin interface just like before.

deprecate archaius2 module

---

.travis.yml

Drop jdk14 and add jdk15 to keep ensure latest version is
tested.

add jdk15 to travis build matrix

---

iep-module-dynconfig/src/main/java/com/netflix/iep/dynconfig/DynamicConfigModule.java
iep-module-dynconfig/src/main/java/com/netflix/iep/dynconfig/DynamicConfigService.java
iep-module-dynconfig/src/test/java/com/netflix/iep/dynconfig/DynamicConfigServiceTest.java

Before the dynconfig module would only have a binding
for the dynamic config manager, now it will also ensure
there is a binding for the base config instance.

add binding for config

---

iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java

We use this value often enough in our code that it should be available through the NetflixEnvironment class.

add insightAccountId method

---

.github/workflows/pr.yml
iep-admin/src/test/java/com/netflix/iep/admin/endpoints/EnvEndpointTest.java

There are multiple environment variables with a prefix
of `JAVA_HOME` on GitHub Actions.

fix test case for github actions

---

iep-guice/src/main/java/com/netflix/iep/guice/Main.java

Add a handler to the generic main helper that will send
uncaught exceptions to the expected logger. Should ensure
they are not missing or sent to an unexpected place when
debugging issues.

log uncaught exceptions by default

---

iep-module-atlas/src/main/java/com/netflix/iep/atlas/AtlasRegistryService.java
iep-module-atlas/src/main/resources/reference.conf
iep-module-atlasaggr/src/main/java/com/netflix/iep/atlasaggr/StatelessRegistryService.java
iep-module-atlasaggr/src/main/resources/reference.conf
iep-nflxenv/README.md
iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java
iep-nflxenv/src/main/resources/reference.conf
iep-nflxenv/src/test/java/com/netflix/iep/NetflixEnvironmentTest.java

Adds methods to NetflixEnvironment helper for extracting
common tags from environment variables. Both of the Atlas
modules now use these helpers to ensure the common tag
behavior will be the same.

add helper methods for common tags

---

.github/workflows/release.yml
.github/workflows/snapshot.yml
project/BuildSettings.scala
project/SonatypeSettings.scala

Update the env variables used for the actions to be more
consistent with gradle projects. For the PGP keys the env
variables expected by `sbt-pgp` are used.

sign jars when publishing

---

iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java
iep-nflxenv/src/main/resources/reference.conf
iep-nflxenv/src/test/java/com/netflix/iep/NetflixEnvironmentTest.java

If users update in place they may not have the newer
environment available. For `nf.account` and `nf.node`
this change will fallback to the older versions.

add fallbacks to legacy env variables

---

iep-module-aws2/src/main/resources/reference.conf

Add overrides to default config to use the global
region for route53 calls. This is required for the
V2 SDK.

use global region for route53

---

iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java
iep-nflxenv/src/main/resources/reference.conf
iep-nflxenv/src/test/java/com/netflix/iep/NetflixEnvironmentTest.java

This is a newer more generic variable and should be
preferred if present.

prefer NETFLIX_REGION over EC2_REGION

---

iep-module-aws/src/main/java/com/netflix/iep/aws/AwsClientFactory.java
iep-module-aws/src/main/java/com/netflix/iep/aws/AwsModule.java
iep-module-aws/src/main/java/com/netflix/iep/aws/Pagination.java
iep-module-awsmetrics/src/main/java/com/netflix/iep/awsmetrics/AwsMetricsModule.java
iep-module-rxnetty/src/main/java/com/netflix/iep/rxnetty/RxNettyModule.java
iep-platformservice/src/main/java/com/netflix/iep/platformservice/PlatformServiceModule.java

Deprecate the main classes for:
- iep-module-aws
- iep-module-awsmetrics
- iep-module-rxnetty
- iep-platformservice
These modules will be removed for 3.0.

deprecate AWS and RxNetty modules

---

iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java

Updates NetflixEnvironment to only access the ConfigManager,
and thus load the typesafe config, if one of the helper
methods that rely on it are called. This avoids static
initialization errors for the NetflixEnvironment class if
there is a bad `application.conf` or `reference.conf` file
in the classpath. This has two benefits:
- For apps that are just relying on telemetry clients that
use the library for getting common tags, the other helpers
will not be accessed and the issues is avoided entirely.
- For apps that do access the methods, the exception will be
thrown to the caller and should be easier to diagnose than
`java.lang.NoClassDefFoundError: Could not initialize class
com.netflix.iep.NetflixEnvironment`.

lazily access typesafe config

---

iep-guice/src/main/java/com/netflix/iep/guice/ClassFactoryProvider.java
iep-guice/src/test/java/com/netflix/iep/guice/GuiceClassFactoryTest.java

It only passes the type and ignores the annotations. To
get the qualifiers to work the qualified type needs to
be wrapped.

add test case for qualifiers with ClassFactory

---

project/BuildSettings.scala

Replace in with [slash syntax].
[slash syntax]: https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash

fix build deprecation warnings

---

build.sbt
iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-module-aws2/src/main/resources/reference.conf
iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
project/Dependencies.scala

Add config settings to specify which client implementation
will get used. Otherwise the SDK will fail when using the
factory and multiple implementations are present.

aws2: allow client impl to be specified

---

build.sbt
project/Dependencies.scala

Jdk16 strongly encapsulates the internals by default
causing problems for older versions of Guice. When
running on a newer JDK, have the build use Guice 5.
For the published library still need to use 4.1.0
to avoid creating problems internally for other
users stuck on old versions.

use guice 5 for newer JDKs

---

iep-module-eureka/src/main/java/com/netflix/iep/eureka/AmazonInfoUtils.java
iep-module-eureka/src/main/java/com/netflix/iep/eureka/CustomEurekaInstanceConfig.java
iep-module-eureka/src/main/java/com/netflix/iep/eureka/EurekaModule.java
iep-module-eureka/src/test/java/com/netflix/iep/eureka/EurekaModuleTest.java

Updates the Eureka module to create the AmazonInfo
from the environment rather than polling the instance
metadata service. For our use-cases the information
doesn't change so continuous polling isn't needed and
the `eureka-client` poller doesn't suppport IDMSv2
preventing us from disabling access without using
tokens.

create AmazonInfo from environment

---

iep-module-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-module-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java
iep-module-aws2/src/test/resources/aws-client-factory.conf

allow overriding the default sdk http client settings and ability to configure retries.
Provides ability to override the [default sdk http configuration](https://github.com/aws/aws-sdk-java-v2/blob/master/http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpConfigurationOption.java#L137) and ability to configure [retries](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java)

allow overriding the default sdk http client settings and ability to configure retries

---

iep-nflxenv/src/main/java/com/netflix/iep/NetflixEnvironment.java
iep-nflxenv/src/test/java/com/netflix/iep/NetflixEnvironmentTest.java

The Mantis tags have long been a part of Atlas metrics common tagging, and
they only appear in the Mantis application clusters, so it is safe to add
them to the default set.
Making this change here, rather than creating a separate set of keys to
cover this use case, means that there will remain one standard source for
Atlas metrics common tags.

add mantis tags to default atlas tag keys

---

iep-module-eureka/src/main/java/com/netflix/iep/eureka/CustomEurekaInstanceConfig.java

Prefer the IP address from the environment rather than
the hostname extracted from the system. On many instances
that hostmame is not resolvable off the instance.

eureka: use ip rather than host by default

---

iep-servergroups/src/test/java/com/netflix/iep/servergroups/GroupServiceTest.java

Cleanup some spurious noise in the test output.

remove println from tests

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/EurekaLoader.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/EurekaLoaderTest.java
iep-servergroups/src/test/resources/eureka-titus-2.json

In some cases with Titus we are seeing unexpected values
that explicitly enumerate various resources.

update validation for Eureka instance type

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/EddaLoader.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/EurekaLoader.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/JsonUtils.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/EddaLoaderTest.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/GroupServiceTest.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/LoaderUtils.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/TestHttpClient.java

The server groups loader could leak native memory if
the gzip stream wasn't closed. Since the json library
will automatically try to close if it hits the end
of stream, the leak would only occur if there was an
error parsing or the parsing stopped before fully
consuming the input.

fix memory leak for compressed responses

---

iep-spring/src/main/java/com/netflix/iep/spring/IepConfiguration.java
iep-spring/src/main/java/com/netflix/iep/spring/Main.java
iep-spring/src/test/java/com/netflix/iep/spring/MainTest.java

Makes it easier to reuse in other contexts where the Main
class may not be used.

move default bindings to configuration class

---

iep-spring/src/main/java/com/netflix/iep/spring/IepConfiguration.java

Can be used for things like healthcheck endpoints to
avoid circular dependency issues.

add binding for ServiceManager provider

---

iep-spring/src/main/java/com/netflix/iep/spring/Main.java
iep-spring/src/test/java/com/netflix/iep/spring/MainTest.java
iep-spring/src/test/java/com/netflix/iep/spring/config/TestConfiguration.java

When explicitly setting up the ApplicationContext the
default IepConfiguration must be explictly added if
desirable. Allows the user to omit it if desirable for
more control.

all default configuration to be omitted

---

iep-spring-leader/src/main/java/com/netflix/iep/leader/LeaderConfiguration.java
iep-spring-leader/src/test/java/com/netflix/iep/leader/LeaderConfigurationTest.java

Use the concrete type in the return value since it
implements both LeaderElector and LeaderStatus. This
avoids errors about missing bindings in some cases.

update leader status binding

---

iep-spring-dynconfig/src/main/java/com/netflix/iep/dynconfig/DynamicConfigConfiguration.java
iep-spring/src/test/java/com/netflix/iep/spring/LifecycleTest.java

Update the dependencies to ensure that the dynamic config service will have been created and synced the remote config before the DynamicConfigManager bean will be created and available for injection. Otherwise the remote settings may not be available on startup.

fix dynamic config injection

---

iep-spring/src/main/java/com/netflix/iep/spring/IepConfiguration.java

This can be used to start gradually moving away from needing to use javax.inject classes.

add binding for ServiceManager supplier

---

iep-spring-atlas/src/main/java/com/netflix/iep/atlas/AtlasConfiguration.java
iep-spring-atlas/src/main/java/com/netflix/iep/atlas/NoSbnCondition.java
iep-spring-atlas/src/test/java/com/netflix/iep/atlas/AtlasConfigurationTest.java

If the SBN metrics properties are detected, then disable the configuration and assume SBN will be used for configuring the registry.

disable Atlas bindings if SBN detected

---

iep-spring-spectatord/src/main/resources/reference.conf

Remove unused configuration settings and include the output location so it is clear how to override if
needed.

cleanup config for spectatord

---

iep-admin/src/main/java/com/netflix/iep/admin/AdminConfig.java
iep-admin/src/main/java/com/netflix/iep/admin/AdminServer.java
iep-admin/src/main/resources/reference.conf
iep-admin/src/test/java/com/netflix/iep/admin/AdminServerTest.java

Add an option to specify the address to listen on. Before it would listen on any local address and could be accessed remotely. Now it will default to only listen on localhost.

admin: option to limit to localhost

---

iep-spring-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-spring-aws2/src/main/resources/reference.conf
iep-spring-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java

Adds a new config option to enable dualstack on the AWS client. For services we commonly use that support dualstack, it is enabled by default.

aws: add option to enable dualstack

---

iep-spring-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-spring-aws2/src/main/resources/reference.conf

Add config with the set of regions where dual-stack endpoints are actually available. This needs to be done in addition to checking if the various services actually support it.

aws: limit dual-stack to allowed regions

---

iep-spring-aws2/src/main/resources/reference.conf

The AWS docs for IPv6 are a bit confusing and not in a single place. For the dualstack API endpoints EC2 and S3 are the only ones that seem to work at this time.

aws: adjust dualstack defaults

---

iep-spring-atlas/src/main/java/com/netflix/iep/atlas/NoSbnCondition.java
iep-spring-atlas/src/test/java/com/netflix/iep/atlas/AtlasConfigurationTest.java

The property name the SBN check uses changed in SBN3. Update it to check for both variants.

disable Atlas binding when using SBN3

---

iep-spring-leader-redis-cluster/src/main/java/com/netflix/iep/leader/redis/RedisClusterLeaderDatabase.java

Instead of logging an error when the leader is already assigned, log it at info. If no leader was present and the transaction failed, we still log an error.

leader-redis: Log failures to acquire leader at info level.

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/EddaLoader.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/EurekaLoader.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/Instance.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/EurekaLoaderTest.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/InstanceTest.java
iep-servergroups/src/test/resources/eureka-ip.json

Update to support Edda instances that only have IPv6 addresses and do not have a private IP address.

servergrous: support v6 only instances

---

iep-servergroups/src/main/java/com/netflix/iep/servergroups/EddaLoader.java
iep-servergroups/src/main/java/com/netflix/iep/servergroups/Instance.java
iep-servergroups/src/test/java/com/netflix/iep/servergroups/EddaLoaderTest.java
iep-servergroups/src/test/resources/edda-ipv6.json

Update Edda parsing to get the IPv6 address for the instances in a server group.

servergroups: extract IPv6 from Edda response

---

iep-admin/src/main/java/com/netflix/iep/admin/HttpEntity.java
iep-admin/src/main/java/com/netflix/iep/admin/HttpResponse.java
iep-admin/src/main/java/com/netflix/iep/admin/JsonEncoder.java
iep-admin/src/main/java/com/netflix/iep/admin/endpoints/SpectatorEndpoint.java
iep-admin/src/test/java/com/netflix/iep/admin/AdminServerTest.java
iep-admin/src/test/java/com/netflix/iep/admin/endpoints/SpectatorEndpointTest.java

Update admin server to incrementally write the items for an iterable to the response rather than first encoding to a byte array in memory.

admin: incrementally stream iterable response

---

iep-admin/src/main/java/com/netflix/iep/admin/RequestHandler.java

Avoid creating an in-memory copy of the entity just to compute the length.

admin: use chunked response

---

project/Dependencies.scala

Revert until performance issue is worked out in jackson 2.17.

jackson 2.16.2

---

iep-spring-aws2/src/main/java/com/netflix/iep/aws2/AwsClientFactory.java
iep-spring-aws2/src/test/java/com/netflix/iep/aws2/AwsClientFactoryTest.java

The RetryPolicy classes are deprecated. Update to use the newer RetryStrategy ([docs]).
[docs]: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/retry-strategy.html

aws2: update to use RetryStrategy

---

project/Dependencies.scala

Move back to older versions. Some internal apps are seeing deadlocks with 6.2.3. Maybe fixed in 6.2.4, but testing is still being done.

spring 6.2.2 and spring-boot 3.4.2

---

.github/workflows/release.yml
project/SonatypeSettings.scala
project/build.properties
project/plugins.sbt

Sonatype is phasing out OSSRH so update the publishing to go to the new central portal.

update to publish to central portal
